[package]
name = "rustcam-simulator"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
rustcam-camera-api = { path = "../../hal/camera/api" }
rustcam-camera-mock = { path = "../../hal/camera/mock" }
rustcam-storage-mock = { path = "../../hal/storage/mock" }
rustcam-transport-mock = { path = "../../hal/transport/mock" }
rustcam-services = { path = "../../service" }
rustcam-applications = { path = "../../app/rustcam" }
