[package]
name = "nxrs-simulator"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
nxrs-camera-api = { path = "../../hal/camera/api" }
nxrs-camera-mock = { path = "../../hal/camera/mock" }
nxrs-storage-mock = { path = "../../hal/storage/mock" }
nxrs-transport-mock = { path = "../../hal/transport/mock" }
nxrs-camera-service = { path = "../../service/camera" }
nxrs-recording-service = { path = "../../service/recording" }
nxrs-telemetry-service = { path = "../../service/telemetry" }
nxrs-applications = { path = "../../app/nxrs" }
