[package]
name = "rustcam-event-demo"
version.workspace = true
edition.workspace = true

[package.metadata.rustcam.firmware]
bin = "event-demo"
command = "event_demo"
priority = 100
stack-size = 65536

[dependencies]
rustcam-navigation-services = { path = "../../service/navigation" }

[[bin]]
name = "event-demo"
path = "src/main.rs"
