[package]
name = "rustcam-native-integration"
version.workspace = true
edition.workspace = true

[dependencies]
rustcam-applications = { path = "../../app/rustcam" }
rustcam-services = { path = "../../service" }
rustcam-camera-api = { path = "../../hal/camera/api" }
rustcam-storage-api = { path = "../../hal/storage/api" }
rustcam-transport-api = { path = "../../hal/transport/api" }
rustcam-camera-native = { path = "../../hal/camera/native" }
rustcam-storage-native = { path = "../../hal/storage/native" }
rustcam-transport-native = { path = "../../hal/transport/native" }
