[package]
name = "nxrs-nuttx-app"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib"]
test = false
doctest = false

[[bin]]
name = "nxrs-nuttx-std-app"
path = "src/main.rs"
required-features = ["std-integration"]

[features]
std-integration = ["dep:nxrs-transport-nuttx"]

[dependencies]
nxrs-camera-api = { path = "../../hal/camera/api" }
nxrs-storage-api = { path = "../../hal/storage/api" }
nxrs-transport-api = { path = "../../hal/transport/api" }
nxrs-services = { path = "../../service" }
nxrs-applications = { path = "../../app/nxrs" }
nxrs-camera-nuttx = { path = "../../hal/camera/nuttx" }
nxrs-storage-nuttx = { path = "../../hal/storage/nuttx" }
nxrs-nuttx-support = { path = "../../hal/support/nuttx" }
nxrs-transport-nuttx = { path = "../../hal/transport/nuttx", optional = true }
