[package]
name = "rustcam-storage"
version.workspace = true
edition.workspace = true

[features]
default = []
mock = ["dep:rustcam-storage-mock"]
native = ["dep:rustcam-storage-native"]
nuttx = ["dep:rustcam-storage-nuttx"]

[dependencies]
rustcam-storage-api = { path = "api" }
rustcam-storage-mock = { path = "mock", optional = true }
rustcam-storage-native = { path = "native", optional = true }
rustcam-storage-nuttx = { path = "nuttx", optional = true }

[package.metadata.rustcam]
kind = "hal-capability"
provider-features = ["mock", "native", "nuttx"]
