[package]
name = "rustcam-applications"
version.workspace = true
edition.workspace = true

[dependencies]
rustcam-camera = { path = "../../hal/camera" }
rustcam-storage = { path = "../../hal/storage" }
rustcam-transport = { path = "../../hal/transport" }
rustcam-services = { path = "../../service" }
rustcam-service-event = { path = "../../service/event", optional = true }

[features]
default = []
cli = ["dep:rustcam-service-event"]

[[bin]]
name = "rustcam"
path = "src/main.rs"
required-features = ["cli"]
