[package]
name = "nxrs-imu"
version.workspace = true
edition.workspace = true

[features]
default = []
mock = ["dep:nxrs-imu-mock"]

[dependencies]
nxrs-imu-api = { path = "api" }
nxrs-imu-mock = { path = "mock", optional = true }

[package.metadata.nxrs]
kind = "hal-capability"
provider-features = ["mock"]
