[package]
name = "nxrs-transport"
version.workspace = true
edition.workspace = true

[features]
default = []
mock = ["dep:nxrs-transport-mock"]
native = ["dep:nxrs-transport-native"]
nuttx = ["dep:nxrs-transport-nuttx"]

[dependencies]
nxrs-transport-api = { path = "api" }
nxrs-transport-mock = { path = "mock", optional = true }
nxrs-transport-native = { path = "native", optional = true }
nxrs-transport-nuttx = { path = "nuttx", optional = true }

[package.metadata.nxrs]
kind = "hal-capability"
provider-features = ["mock", "native", "nuttx"]
